POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = azoteq_iqs9150

RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = ws2812

WS2812_DRIVER_REQUIRED = yes
WS2812_DRIVER = bitbang

CONSOLE_ENABLE = yes
POINTING_DEVICE_DEBUG = yes

